### ISSUE TITLE
[FEAT] 푸터 생성

### ISSUE THREAD

**Issue by ramrami-B** [moofarm/ssuckssuck-frontend#11]
## 💡 Feature Issue

푸터 생성
<img width="693" alt="image" src="https://github.com/moofarm/ssuckssuck-frontend/assets/74824057/7bd901c6-5227-49f0-a5e1-33284a4b7f9c">

## 🌿 To-do

- [x] 페이지 하단 영역에 푸터 생성
- [x] Contact 부분을 누르면 메일창을 띄워 메일을 보낼 수 있다.
- [x] 이용약관, 개인정보처리방침, 서비스소개를 누르면 관련 노션 페이지로 이동한다.
- [x] 테스트

**Comment by ramrami-B** [comment]
TODO: 스토리북으로 테스트 했을 때 footer의 widthrk 650px이하로 떨어질 때 깨짐 발생 => 반응형 UI 개발시 참고하기!
