### ISSUE TITLE
[FEAT] 검색 컴포넌트 생성

### ISSUE THREAD

**Issue by ramrami-B** [moofarm/ssuckssuck-frontend#21]
## 🌳 Description
<img width="514" alt="image" src="https://github.com/moofarm/ssuckssuck-frontend/assets/74824057/f8336ee8-02ce-46f9-884f-e3c5b3bbffc9">

## 🌟 Todo
- [ ] 검색 컴포넌트 생성
- [ ] 헤더의 검색 아이콘 누르면 검색 컴포넌트 나오기
- [ ] 'x' 아이콘 누르면 닫힘
- [ ] 검색어 입력시 검색 API 호출
- [ ] 결과 하단에 띄우기
