### ISSUE TITLE
[FEAT] 카드 컴포넌트 생성

### ISSUE THREAD

**Issue by alex-koko** [moofarm/ssuckssuck-frontend#30]
## 🌳 Description
1. 카드 컴포넌트 
![image](https://github.com/moofarm/ssuckssuck-frontend/assets/86093028/f7631210-1c05-4798-9eba-2cd6b6dd2a73)
(사진이 배경에 들어감)

2. 카드 모달 (해당 사진이 확대됨)
![image](https://github.com/moofarm/ssuckssuck-frontend/assets/86093028/607eaf4b-49a8-4481-b491-c389507e046a)
![image](https://github.com/moofarm/ssuckssuck-frontend/assets/86093028/d7adbfc8-a881-4576-8866-acbcf0247603)
(내가 올린 것- 수정하기 버튼, 남이 올린 것-신고하기 버튼)

## 🌟 Todo

- [x] 카드 컴포넌트 만들기 (이미지)
- [x] 카드 컴포넌트 추가 버튼 만들기 (+) 
- [x] 카드 모달 만들기
- [x] 카드 모달에 사진 업로드 기능 넣기
- [ ] 작성자에 따라 수정하기, 신고하기 버튼 바뀌도록 구현
- [ ] 플러스 버튼으로 이미지 추가시 서버로 전송되도록
