### ISSUE TITLE
[Feat] 랜딩페이지 생성

### ISSUE THREAD

**Issue by ramrami-B** [moofarm/ssuckssuck-frontend#36]
## 🌳 Description
![image](https://github.com/moofarm/ssuckssuck-frontend/assets/74824057/665960d4-5870-4270-9dcc-12b899d1448e)

## 🌟 Todo

- [ ] 소셜로그인 페이지 만들기
- [ ] 회원가입 시 입력하는 모달 컴포넌트 만들기
- [ ] 소셜 로그인 구현
- [ ] 회원가입 구현

## 📝 Reference
카카오 로그인
https://developers.kakao.com/tool/resource/login

네이버 로그인
https://developers.naver.com/docs/login/bi/bi.md

구글 로그인
https://developers.google.com/identity/branding-guidelines?hl=ko
