### ISSUE TITLE
[FEAT] 회원 가입

### ISSUE THREAD

**Issue by ramrami-B** [moofarm/ssuckssuck-frontend#52]
## 💡 Feature Issue
회원가입 기능 구현

## 🌿 To-do

- [x] 닉네임 중복 확인 (landing-1)
- [x] 메인 카테고리 선택 (landing-2)
- [x] 메인 카테고리 중 "기타" 선택하면 바로 회원가입
- [x] skip 누르면 메인 카테고리, 서브 카테고리 둘 다 빈 문자열로 지정
- [x] 서브 카테고리 선택 (landing-3)
- [x] "완료" 버튼 누르면 회원 가입 완료
