### ISSUE TITLE
[FEAT] 페이지 레이아웃 만들기

### ISSUE THREAD

**Issue by ramrami-B** [moofarm/ssuckssuck-frontend#6]
## 🌳 Description

피그마 예시
<img width="573" alt="image" src="https://github.com/moofarm/ssuckssuck-frontend/assets/74824057/e42f9a5f-99dc-4524-b865-6ee2fb65bff0">

## 🌟 Todo

- [ ] 헤더 컴포넌트 생성
- [ ] 푸터 컴포넌트 생성
- [ ] routes.js 수정 및 페이지 레이아웃 생성
